// <auto-generated />
using System;
using BookCatalog.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCatalog.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCatalog.Core.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Douglas Adams",
                            CreatedDate = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780345391803",
                            IsActive = true,
                            PublishedYear = 1979,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Gamma, Helm, Johnson, Vlissides",
                            CreatedDate = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780201633610",
                            IsActive = true,
                            PublishedYear = 1994,
                            Title = "Design Patterns: Elements of Reusable OO Software"
                        },
                        new
                        {
                            Id = 3,
                            Author = "David Thomas, Andrew Hunt",
                            CreatedDate = new DateTime(2001, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780135957059",
                            IsActive = true,
                            PublishedYear = 1999,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            CreatedDate = new DateTime(2008, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780132350884",
                            IsActive = true,
                            PublishedYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.R.R. Tolkien",
                            CreatedDate = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780618640157",
                            IsActive = true,
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Michael Crichton",
                            CreatedDate = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9780345370778",
                            IsActive = true,
                            PublishedYear = 1990,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Andy & Larry Wachowski",
                            CreatedDate = new DateTime(2001, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9781557044488",
                            IsActive = false,
                            PublishedYear = 2001,
                            Title = "The Matrix: The Shooting Script"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
